// mutablelib — ml.h
//
// Includes every component. Handy for quick experiments; in a real module,
// include only the headers you use (some carry large tables, and every
// include adds compile time).

#ifndef ML_ML_H_
#define ML_ML_H_

#include "ml/analysis/onset_detector.h"
#include "ml/core/math.h"
#include "ml/core/random.h"
#include "ml/core/tables.h"
#include "ml/core/units.h"
#include "ml/drums/analog_kick.h"
#include "ml/drums/analog_snare.h"
#include "ml/drums/fm_drum.h"
#include "ml/drums/hihat.h"
#include "ml/drums/synth_kick.h"
#include "ml/drums/synth_snare.h"
#include "ml/dynamics/compressor.h"
#include "ml/dynamics/follower.h"
#include "ml/dynamics/lpg.h"
#include "ml/dynamics/vactrol.h"
#include "ml/filter/dc_blocker.h"
#include "ml/filter/hilbert.h"
#include "ml/filter/one_pole.h"
#include "ml/filter/svf.h"
#include "ml/filter/vowel.h"
#include "ml/fx/chorus.h"
#include "ml/fx/decimator.h"
#include "ml/fx/delay_line.h"
#include "ml/fx/diffuser.h"
#include "ml/fx/ensemble.h"
#include "ml/fx/fx_engine.h"
#include "ml/fx/limiter.h"
#include "ml/fx/overdrive.h"
#include "ml/fx/pitch_shifter.h"
#include "ml/fx/reverb.h"
#include "ml/fx/wavefolder.h"
#include "ml/mod/bouncing_ball.h"
#include "ml/mod/clock_to_ramp.h"
#include "ml/mod/envelope.h"
#include "ml/mod/hysteresis_quantizer.h"
#include "ml/mod/lag.h"
#include "ml/mod/lorenz.h"
#include "ml/mod/quantizer.h"
#include "ml/mod/random_sequence.h"
#include "ml/mod/slope.h"
#include "ml/noise/clocked_noise.h"
#include "ml/noise/dust.h"
#include "ml/noise/particle.h"
#include "ml/noise/smooth_random.h"
#include "ml/osc/basic.h"
#include "ml/osc/formant.h"
#include "ml/osc/grainlet.h"
#include "ml/osc/harmonic.h"
#include "ml/osc/polyblep.h"
#include "ml/osc/sine.h"
#include "ml/osc/string_synth.h"
#include "ml/osc/variable_shape.h"
#include "ml/osc/vosim.h"
#include "ml/osc/wavetable.h"
#include "ml/osc/z_osc.h"
#include "ml/physical/modal_resonator.h"
#include "ml/physical/plucker.h"
#include "ml/physical/string.h"
#include "ml/physical/tube.h"
#include "ml/spectral/fm_operators.h"
#include "ml/spectral/vocoder.h"
#include "ml/spectral/xmod.h"

#endif  // ML_ML_H_
