// partials — partials.h
//
// Includes every component. Handy for quick experiments; in a real module,
// include only the headers you use (some carry large tables, and every
// include adds compile time).

#ifndef PT_PARTIALS_H_
#define PT_PARTIALS_H_

#include "pt/analysis/onset_detector.h"
#include "pt/core/math.h"
#include "pt/core/random.h"
#include "pt/core/tables.h"
#include "pt/core/units.h"
#include "pt/drums/analog_kick.h"
#include "pt/drums/analog_snare.h"
#include "pt/drums/fm_drum.h"
#include "pt/drums/hihat.h"
#include "pt/drums/synth_kick.h"
#include "pt/drums/synth_snare.h"
#include "pt/dynamics/compressor.h"
#include "pt/dynamics/follower.h"
#include "pt/dynamics/lpg.h"
#include "pt/dynamics/vactrol.h"
#include "pt/filter/dc_blocker.h"
#include "pt/filter/hilbert.h"
#include "pt/filter/one_pole.h"
#include "pt/filter/svf.h"
#include "pt/filter/vowel.h"
#include "pt/fx/chorus.h"
#include "pt/fx/decimator.h"
#include "pt/fx/delay_line.h"
#include "pt/fx/diffuser.h"
#include "pt/fx/ensemble.h"
#include "pt/fx/fx_engine.h"
#include "pt/fx/limiter.h"
#include "pt/fx/overdrive.h"
#include "pt/fx/pitch_shifter.h"
#include "pt/fx/reverb.h"
#include "pt/fx/wavefolder.h"
#include "pt/mod/bouncing_ball.h"
#include "pt/mod/clock_to_ramp.h"
#include "pt/mod/envelope.h"
#include "pt/mod/hysteresis_quantizer.h"
#include "pt/mod/lag.h"
#include "pt/mod/lorenz.h"
#include "pt/mod/quantizer.h"
#include "pt/mod/random_sequence.h"
#include "pt/mod/slope.h"
#include "pt/noise/clocked_noise.h"
#include "pt/noise/dust.h"
#include "pt/noise/particle.h"
#include "pt/noise/smooth_random.h"
#include "pt/osc/basic.h"
#include "pt/osc/formant.h"
#include "pt/osc/grainlet.h"
#include "pt/osc/harmonic.h"
#include "pt/osc/polyblep.h"
#include "pt/osc/sine.h"
#include "pt/osc/string_synth.h"
#include "pt/osc/variable_shape.h"
#include "pt/osc/vosim.h"
#include "pt/osc/wavetable.h"
#include "pt/osc/z_osc.h"
#include "pt/physical/modal_resonator.h"
#include "pt/physical/plucker.h"
#include "pt/physical/string.h"
#include "pt/physical/tube.h"
#include "pt/sample/audio_buffer.h"
#include "pt/sample/wav.h"
#include "pt/spectral/fm_operators.h"
#include "pt/spectral/vocoder.h"
#include "pt/spectral/xmod.h"

#endif  // PT_PARTIALS_H_
